"""user_model_modify_constraints

Revision ID: 55fe796eaab8
Revises: 36a0ae16c788
Create Date: 2023-05-28 15:54:39.618368

"""
from alembic import op

# import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "55fe796eaab8"
down_revision = "36a0ae16c788"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("users_id_expiration_key", "users", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("users_id_expiration_key", "users", ["id_expiration"])
    # ### end Alembic commands ###
