"""permission_model_initial_migration

Revision ID: 634c2969cd54
Revises: bccfa91111a4
Create Date: 2023-06-11 14:32:47.108037

"""
import sqlalchemy as sa
from alembic import op

import app

# revision identifiers, used by Alembic.
revision = "634c2969cd54"
down_revision = "bccfa91111a4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permissions",
        sa.Column("id", app.utils.guid.GUID(), nullable=False),
        sa.Column("resource_id", app.utils.guid.GUID(), nullable=False),
        sa.Column("mode", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("updated_by", sa.String(), nullable=False),
        sa.Column("deleted_by", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["resource_id"],
            ["resources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_permissions_resource_id"), "permissions", ["resource_id"], unique=False
    )
    op.create_index(
        "resource_permission_index", "permissions", ["resource_id", "mode"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("resource_permission_index", table_name="permissions")
    op.drop_index(op.f("ix_permissions_resource_id"), table_name="permissions")
    op.drop_table("permissions")
    # ### end Alembic commands ###
