"""user_otp_model_initial_migration

Revision ID: 6910b7845d2c
Revises: 55fe796eaab8
Create Date: 2023-06-03 13:48:07.927273

"""
import sqlalchemy as sa
from alembic import op

import app

# revision identifiers, used by Alembic.
revision = "6910b7845d2c"
down_revision = "55fe796eaab8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users_otp",
        sa.Column("id", app.utils.guid.GUID(), nullable=False),
        sa.Column("user_id", app.utils.guid.GUID(), nullable=False),
        sa.Column("otp_code", sa.String(), nullable=True),
        sa.Column("otp_code_expiration", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sec_token", sa.String(), nullable=True),
        sa.Column("sec_token_expiration", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", app.utils.guid.GUID(), nullable=True),
        sa.Column("updated_by", app.utils.guid.GUID(), nullable=True),
        sa.Column("deleted_by", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_users_otp_otp_code"), "users_otp", ["otp_code"], unique=False
    )
    op.create_index(op.f("ix_users_otp_user_id"), "users_otp", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_otp_user_id"), table_name="users_otp")
    op.drop_index(op.f("ix_users_otp_otp_code"), table_name="users_otp")
    op.drop_table("users_otp")
    # ### end Alembic commands ###
